# Spec locations
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '9.3'

# Public Pods
def app_pods
  pod 'JsonInflator', '~> 0.6.2'
end

target :"SlicingGame" do
  app_pods
end