# Spec locations
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '9.3'

# Public Pods
def app_pods
  # Network pods
  pod 'Alamofire', '~> 4.9.1'

  # App framework pods
  pod 'DynamicAppConfig', '~> 1.3.4'
  pod 'UniLayout', '~> 0.4.6'
  pod 'JsonInflator', '~> 0.6.2'
end

target :"SlicingGame" do
  app_pods
end